################################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza             #
#      SPDX-License-Identifier:  GPL-2.0-only                                  #
################################################################################
configs:
  nginx.conf:
    file: /run/configs/etc/nginx/nginx.conf
secrets:
  default.conf:
    file: /run/secrets/etc/nginx/conf.d/default.conf
services:
  nlb:
    configs:
    - mode: 0400
      source: nginx.conf
      target: /etc/nginx/nginx.conf
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
        reservations:
          cpus: "0.1"
          memory: 100M
    expose:
    - "8080"
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 30s
      test: ["CMD-SHELL", "netstat -ln | grep -q 8080"]
      timeout: 1s
    image: academiaonline/nginx:8.2
    ports:
    - "port_master:8080"
    secrets:
    - mode: 0400
      source: default.conf
      target: /etc/nginx/conf.d/default.conf
version: "3.8"
################################################################################
